### ISSUE TITLE
Does this work with plain Couch? Do we want to make it work with it?

### ISSUE THREAD

**Issue by danse** [eHealthAfrica/angular-eha.couchdb-auth#23]
Maybe docs are not updated about [a critical point](https://github.com/eHealthAfrica/angular-eha.couchdb-auth#angular-ehacouchdb-auth): this auth module works with a bearer token, which is not supported by plain Couch. What do we want to do? Should we have a separated module for cases when we are authenticating directly against Couch?

**Comment by danse** [comment]
@patriciagarcia now that you are back, do you have anything to say about this? You were authoring also the original https://github.com/eHealthAfrica/ehealth-couch-auth

**Comment by tthew** [comment]
@danse it _should_ work with plain couchdb instance.  When you sign in (POST /_session) couchdb will respond with a cookie and the browser should just behave as normal.  

Is couchdb complaining about the `bearer` header?

If so, I think it's perhaps because the poor docs / config interface is tripping you up. The interceptor will only add the bearer token to hosts for which you want to send it (see: https://github.com/eHealthAfrica/angular-eha.couchdb-auth/blob/master/src/http-interceptor.js#L25) , so if you configure that as such (i.e. empty), then it shouldn't send a bearer header and couchdb shouldn't complain.

**Comment by tthew** [comment]
One point to note is that 'password reset' won't work without compatible middleware as couchdb does not provide that functionality https://github.com/eHealthAfrica/angular-eha.couchdb-auth#resetpasswordparams

**Comment by danse** [comment]
Cool, i just wanted to be sure about the intended behaviour. This issue is about the intentions, so if something is missing we can track it in another issue. I do not remember whether i was getting some runtime errors, but i think that i should specify an URL for the interceptor anyway, because this is the way to have the interceptor handling `401` errors for connections towards that domain, right?

**Comment by tthew** [comment]
@danse aha yeah you're right; https://github.com/eHealthAfrica/angular-eha.couchdb-auth/blob/master/src/http-interceptor.js#L49

This is a bug.
