### ISSUE TITLE
Should admins always be authorised?

### ISSUE THREAD

**Issue by tlvince** [eHealthAfrica/angular-eha.couchdb-auth#28]
I expected `require<Role>User` and `eha-show-for-role` to always pass for admins. Would you agree?

**Comment by tthew** [comment]
Hmm. Good question.  I'm not sure.  

When you say admin, do you mean a 'couchdb' admin?

**Comment by tlvince** [comment]
I mean any user who has a role that's included in the `adminRoles` list.

**Comment by tthew** [comment]
Apologies, been a while since I've looked at this. Yes, then I think that would make sense & I _think_ (at a quick glance) that it might be a one-liner https://github.com/eHealthAfrica/angular-eha.couchdb-auth/blob/master/src/auth.service.js#L243

**Comment by patriciagarcia** [comment]
Sounds like a good idea, I think it would require some changes in mNutrition (which is using this module) but the result would be more clear and generic.

For @tthew (that knows mNutrition) and as notes for myself:

One example of how this work now in mnutrition (which is using this library):
* admin users have roles `admin` and `data_providers`, because of the role `admin` they can edit dashboard settings and because of the `data_reviewers` role they can see uploaded reports. Having the role `admin` also means they belong to a higher level organisation, which means they can see reports from all agencies. However if you remove the `data_reviewers` role they won't be able to see any reports.

* with the new meaning of `admin` (admins can do everything), we'll have users with a single role `admin` that can add, see all reports and edit settings. If we have users that should be able to edit settings but not adding reports, for example, we'll have to create a different role for them (no `admin`).

* we should implement this higher level organisation in a different way, to allow users that have access to limited functionality (ex: no editing of settings) but can see reports from all agencies, like the ministry of health.
